In [1]:
import pandas
import numpy
import re
import sys
!{sys.executable} -m pip install bs4
!{sys.executable} -m pip install lxml
from bs4 import BeautifulSoup

Requirement already satisfied: bs4 in /opt/anaconda3/lib/python3.7/site-packages (0.0.1)
Requirement already satisfied: beautifulsoup4 in /opt/anaconda3/lib/python3.7/site-packages (from bs4) (4.8.0)
Requirement already satisfied: soupsieve>=1.2 in /opt/anaconda3/lib/python3.7/site-packages (from beautifulsoup4->bs4) (1.9.3)
Requirement already satisfied: lxml in /opt/anaconda3/lib/python3.7/site-packages (4.4.1)

# Part 1: 2019 MLB Data of All 30 Teams (40 Man Rosters)

In [2]:
# Estabolish data collection lists
file_teams = ['ARI', 'ATL', 'BAL', 'BOS', 'CHC', 'CHW', 'CIN', 'CLE', 'COL', 'DET', 'HOU', 'KCR', 'LAA', 'LAD', 'MIA', 'MIL', 'MIN', 'NYM', 'NYY', 'OAK', 'PHI', 'PIT', 'SDP', 'SEA', 'SFG', 'STL', 'TBR', 'TEX', 'TOR', 'WAS']
mlb_teams = []
mlb_names = []
mlb_ages = []
mlb_bats = []
mlb_throws = []
mlb_heights = []
mlb_weights = []
mlb_years = []
mlb_games = []
mlb_p_games = []
mlb_c_games = []
mlb_1b_games = []
mlb_2b_games = []
mlb_3b_games = []
mlb_ss_games = []
mlb_lf_games = []
mlb_cf_games = []
mlb_rf_games = []
mlb_war = []
mlb_sal = []

In [3]:
# Loop through each team's html file
for i in file_teams:
    file = '19_' + i + '.html'
    
    # Soupify html files and navigate data rows 
    with open(file) as file_reader:
        soup = BeautifulSoup(file_reader, "lxml")
        table = soup.find(lambda tag: tag.name=='table' and tag.has_attr('id') and tag['id']=="appearances")
        table_body = table.find('tbody')
        rows = table_body.find_all('tr')
        
        # Loop through each row (player) and gather data points
        for row in rows:
            name = row.find('a').get_text()
            age = row.find('td', attrs={"data-stat" : "age" }).get_text()
            bat = row.find('td', attrs={"data-stat" : "bats" }).get_text()
            throw = row.find('td', attrs={"data-stat" : "throws" }).get_text()
            height = row.find('td', attrs={"data-stat" : "height" }).get_text()
            weight = row.find('td', attrs={"data-stat" : "weight" }).get_text()
            years = row.find('td', attrs={"data-stat" : "experience" }).get_text()
            games = row.find('td', attrs={"data-stat" : "G_all" }).get_text()
            P_games = row.find('td', attrs={"data-stat" : "G_p_app" }).get_text()
            C_games = row.find('td', attrs={"data-stat" : "G_c" }).get_text()
            FB_games = row.find('td', attrs={"data-stat" : "G_1b" }).get_text()
            SB_games = row.find('td', attrs={"data-stat" : "G_2b" }).get_text()
            TB_games = row.find('td', attrs={"data-stat" : "G_3b" }).get_text()
            SS_games = row.find('td', attrs={"data-stat" : "G_ss" }).get_text()
            LF_games = row.find('td', attrs={"data-stat" : "G_lf_app" }).get_text()
            CF_games = row.find('td', attrs={"data-stat" : "G_cf_app" }).get_text()
            RF_games = row.find('td', attrs={"data-stat" : "G_rf_app" }).get_text()
            war = row.find('td', attrs={"data-stat" : "WAR" }).get_text()
            sal = row.find('td', attrs={"data-stat" : "Salary" }).get_text()
            
            # Add data points to corresponding data lists
            mlb_teams.append(i)
            mlb_names.append(name)
            mlb_ages.append(age)
            mlb_bats.append(bat)
            mlb_throws.append(throw)
            mlb_heights.append(height)
            mlb_weights.append(weight)
            mlb_years.append(years)
            mlb_games.append(games)
            mlb_p_games.append(P_games)
            mlb_c_games.append(C_games)
            mlb_1b_games.append(FB_games)
            mlb_2b_games.append(SB_games)
            mlb_3b_games.append(TB_games)
            mlb_ss_games.append(SS_games)
            mlb_lf_games.append(LF_games)
            mlb_cf_games.append(CF_games)
            mlb_rf_games.append(RF_games)
            mlb_war.append(war)
            mlb_sal.append(sal)

In [4]:
# Generate dataframe MLBPlayerInfo with data lists and column labels
MLBPlayerInfo = pandas.DataFrame({ 'Team' : mlb_teams,
                                 'Name' : mlb_names,
                                 'Age' : mlb_ages,
                                 'Bats' : mlb_bats,
                                 'Throws' : mlb_throws,
                                 'Height' : mlb_heights,
                                 'Weight' : mlb_weights,
                                 'Years in League' : mlb_years,
                                 'Games Played' : mlb_games,
                                 'Games as P' : mlb_p_games,
                                 'Games as C' : mlb_c_games,
                                 'Games as 1B' : mlb_1b_games,
                                 'Games as 2B' : mlb_2b_games,
                                 'Games as 3B' : mlb_3b_games,
                                 'Games as SS' : mlb_ss_games,
                                 'Games as LF' : mlb_lf_games,
                                 'Games as CF' : mlb_cf_games,
                                 'Games as RF' : mlb_rf_games,
                                 'WAR' : mlb_war,
                                 'Salary' : mlb_sal})

In [5]:
MLBPlayerInfo.head(50)

,Team,Name,Age,Bats,Throws,Height,Weight,Years in League,Games Played,Games as P,Games as C,Games as 1B,Games as 2B,Games as 3B,Games as SS,Games as LF,Games as CF,Games as RF,WAR,Salary
0,ARI,Nick Ahmed,29,R,R,"6' 2""",195,6,158,0,0,0,0,0,158,0,0,0,4.3,"$3,663,000"
1,ARI,Abraham Almonte,30,B,R,"5' 9""",210,7,17,0,0,0,0,0,0,0,3,9,0.6,
2,ARI,Matt Andriese,29,R,R,"6' 2""",225,5,54,54,0,0,0,0,0,0,0,0,-0.1,"$920,000"
3,ARI,Alex Avila,32,L,R,"5' 11""",210,11,63,2,54,0,0,0,0,0,0,0,1.4,"$4,250,000"
4,ARI,Archie Bradley,26,R,R,"6' 4""",225,5,66,66,0,0,0,0,0,0,0,0,0.9,"$1,830,000"
5,ARI,Andrew Chafin,29,R,L,"6' 2""",225,6,77,77,0,0,0,0,0,0,0,0,0.7,"$1,945,000"
6,ARI,Taylor Clarke,26,R,R,"6' 4""",200,1st,23,23,0,0,0,0,0,0,0,0,-0.2,
7,ARI,Stefan Crichton,27,R,R,"6' 3""",200,2,28,28,0,0,0,0,0,0,0,0,0.3,
8,ARI,Kevin Cron,26,R,R,"6' 5""",250,1st,39,0,0,12,0,1,0,0,0,0,0.1,
9,ARI,Jon Duplantier,24,L,R,"6' 4""",225,1st,15,15,0,0,0,0,0,0,0,0,0.2,
10,ARI,Jarrod Dyson,34,L,R,"5' 9""",165,10,130,0,0,0,0,0,0,16,103,21,1.4,"$3,750,000"
11,ARI,Eduardo Escobar,30,B,R,"5' 10""",185,9,158,0,0,0,33,144,0,0,0,0,3.6,"$6,166,666"
12,ARI,Wilmer Flores,27,R,R,"6' 3""",205,7,89,0,0,16,64,0,0,0,0,0,0.9,"$3,750,000"
13,ARI,Zac Gallen,23,R,R,"6' 2""",191,1st,8,8,0,0,0,0,0,0,0,0,1.2,
14,ARI,Kevin Ginkel,25,L,R,"6' 4""",210,1st,25,25,0,0,0,0,0,0,0,0,0.7,
15,ARI,Zack Godley,29,R,R,"6' 3""",240,5,27,27,0,0,0,0,0,0,0,0,-1.0,"$609,400"
16,ARI,Zack Greinke,35,R,R,"6' 2""",200,16,26,23,0,0,0,0,0,0,0,0,4.9,"$34,500,000"
17,ARI,Yoshihisa Hirano,35,R,R,"6' 1""",185,2,62,62,0,0,0,0,0,0,0,0,-0.4,"$3,000,000"
18,ARI,Greg Holland,33,R,R,"5' 10""",205,9,40,40,0,0,0,0,0,0,0,0,0.0,"$3,250,000"
19,ARI,Adam Jones,33,R,R,"6' 2""",215,14,137,0,0,0,0,0,0,0,1,130,-0.6,"$3,000,000"
20,ARI,Caleb Joseph,33,R,R,"6' 3""",180,6,20,2,16,0,0,0,0,0,0,0,0.0,
21,ARI,Carson Kelly,24,R,R,"6' 2""",220,4,111,0,101,0,0,1,0,0,0,0,1.7,"$560,000"
22,ARI,Merrill Kelly,30,R,R,"6' 2""",190,1st,32,32,0,0,0,0,0,0,0,0,0.4,"$2,000,000"
23,ARI,Matt Koch,28,L,R,"6' 3""",215,4,9,9,0,0,0,0,0,0,0,0,-0.6,"$567,600"
24,ARI,Jake Lamb,28,L,R,"6' 3""",215,6,78,0,0,24,0,36,0,0,0,0,0.2,"$4,825,000"
25,ARI,Mike Leake,31,R,R,"5' 10""",170,10,10,10,0,0,0,0,0,0,0,0,-0.6,
26,ARI,Domingo Leyba,23,B,R,"5' 11""",160,1st,21,0,0,0,8,1,2,0,0,0,0.2,
27,ARI,Tim Locastro,26,R,R,"6' 1""",200,3,91,0,0,0,0,0,0,34,20,25,0.8,
28,ARI,Yoan López,26,R,R,"6' 3""",185,2,70,70,0,0,0,0,0,0,0,0,0.5,"$556,900"
29,ARI,Ketel Marte,25,B,R,"6' 1""",165,5,144,0,0,0,83,0,11,0,96,0,7.2,"$2,400,000"
30,ARI,T.J. McFarland,30,L,L,"6' 3""",220,7,51,51,0,0,0,0,0,0,0,0,-0.7,"$1,400,000"
31,ARI,John Ryan Murphy,28,R,R,"5' 11""",205,7,25,2,18,0,0,0,0,0,0,0,-0.1,"$900,000"
32,ARI,Joel Payamps,25,R,R,"6' 2""",200,1st,2,2,0,0,0,0,0,0,0,0,0.0,
33,ARI,David Peralta,31,L,L,"6' 1""",210,6,99,0,0,0,0,0,0,93,0,0,1.9,"$7,000,000"
34,ARI,Robbie Ray,27,L,L,"6' 2""",195,6,34,33,0,0,0,0,0,0,0,0,0.8,"$6,050,000"
35,ARI,Josh Rojas,25,L,R,"6' 1""",185,1st,41,0,0,0,1,0,0,33,0,6,-0.1,
36,ARI,Robby Scott,29,B,L,"6' 3""",220,4,11,11,0,0,0,0,0,0,0,0,0.0,
37,ARI,James Sherfy,27,R,R,"6' 0""",175,3,17,17,0,0,0,0,0,0,0,0,-0.3,
38,ARI,Blake Swihart,27,B,R,"6' 1""",200,5,31,0,0,1,0,0,0,10,0,9,-0.9,
39,ARI,Yasmany Tomás,28,R,R,"6' 2""",250,4,4,0,0,0,0,0,0,0,0,0,-0.2,"$15,500,000"
40,ARI,Ildemaro Vargas,27,B,R,"6' 0""",170,3,92,0,0,0,48,14,4,1,0,1,0.7,"$557,000"
41,ARI,Christian Walker,28,R,R,"6' 0""",220,5,152,0,0,142,0,0,0,0,0,0,3.0,"$559,800"
42,ARI,Taijuan Walker,26,R,R,"6' 4""",235,7,1,1,0,0,0,0,0,0,0,0,0.1,"$5,025,000"
43,ARI,Luke Weaver,25,R,R,"6' 2""",170,4,13,12,0,0,0,0,0,0,0,0,1.6,"$581,300"
44,ARI,Alex Young,25,L,L,"6' 2""",205,1st,17,17,0,0,0,0,0,0,0,0,0.4,
45,ATL,Ronald Acuna Jr.,21,R,R,"6' 0""",180,2,156,0,0,0,0,0,0,46,100,35,5.7,"$560,000"
46,ATL,Ozzie Albies,22,B,R,"5' 8""",165,3,160,0,0,0,158,0,0,0,0,0,5.2,"$575,000"
47,ATL,Jesse Biddle,27,L,L,"6' 5""",220,2,15,15,0,0,0,0,0,0,0,0,-0.3,"$575,000"
48,ATL,Jerry Blevins,35,L,L,"6' 6""",190,13,45,45,0,0,0,0,0,0,0,0,0.3,
49,ATL,Johan Camargo,25,B,R,"6' 0""",195,3,98,0,0,1,4,18,25,11,0,5,-0.6,"$575,000"

# Part 2: MLS Soccer Data of Current Players

In [6]:
# Creating arrays which will be filled with scraped data. These will be the column names in the dataframe I will build.

names = []
positions = []
heights = []
weights = []
ages = []

In [7]:
# Creating an array with names of all the files that need to be scraped. I will loop through these when I scrape from them.

files= []
for x in range(0,25):
    file = ('Players _ MLSsoccer'+ str(x) + '.html')
    files.append(file)

In [8]:
# Looping through each file and using BeautifulSoup to scrape player name, height, weight, position, and age. I add those
# scraped parameters to their respecrive arrays

for file in files:
    with open(file, encoding = 'utf-8') as file_reader:
        soup = BeautifulSoup(file_reader, "lxml")
        players = soup.find_all(class_ = 'row')  
        for player in players:
            try:
                name = player.find('div', class_ = 'name').get_text()
                position = player.find('span', class_ = 'position').get_text()
                height = player.find('span', class_ = 'stat height').get_text()
                weight = player.find('span', class_ = 'stat weight').get_text()
                age = player.find('span', class_ = 'stat age').get_text()
                
            except:
                continue
            names.append(name)
            positions.append(position)
            heights.append(height)
            weights.append(weight)
            ages.append(age)

In [9]:
#Building the dataframe with the arrays. They have now been filled with scraped data.

MLSPlayerInfo = pandas.DataFrame({ 'Name' : names,
                                  'Position' : positions,
                                  'Height' : heights,
                                  'Weight' : weights,
                                  'Age' : ages})

In [10]:
MLSPlayerInfo.head(50)

                  Name    Position  Height Weight Age
0         Robert Beric     Forward   6' 2"    183  28
1        Boris Sekulic    Defender   6' 2"    161  28
2     Brenden Aaronson  Midfielder  5' 10"    148  19
3    Saad Abdul-Salaam    Defender   6' 4"    185  28
4         Mohammed Abu  Midfielder   5' 7"    150  28
5       Lalas Abubakar    Defender   6' 1"    185  25
6          David Accam     Forward   5' 9"    154  29
7      Nicolas Acevedo  Midfielder   5' 8"    160  21
8               Achara  Midfielder  5' 10"    161  22
9        George Acosta  Midfielder   5' 7"    130  20
10       Danilo Acosta    Defender  5' 11"    170  22
11        Bryan Acosta  Midfielder   5' 8"    161  26
12       Kellyn Acosta  Midfielder  5' 10"    150  24
13          Kyle Adams    Defender   6' 2"    180  23
14            Mo Adams  Midfielder   5' 6"    165  23
15         Fanendo Adi     Forward   6' 4"    185  29
16           Ali Adnan    Defender   6' 1"    180  26
17      Harrison Afful    Defender   5' 6"    128  33
18        Juan Agudelo     Forward   6' 1"    183  27
19            Jose Aja    Defender   6' 4"    185  26
20    Jacob Akanyirige    Defender  5' 11"    157  18
21      Tesho Akindele     Forward   6' 1"    170  28
22         Ayo Akinola     Forward  5' 10"    182  20
23      Oswaldo Alanis    Defender   6' 1"    180  31
24        Fatai Alashe  Midfielder   6' 0"    170  26
25     Ignacio Aliseda  Midfielder   5' 7"    152  20
26                Nani  Midfielder  5' 10"    146  33
27      Osvaldo Alonso  Midfielder  5' 11"    165  34
28       Jozy Altidore     Forward   6' 0"    175  30
29      Efrain Alvarez  Midfielder   5' 8"    150  17
30       Luis Amarilla     Forward   6' 0"    163  24
31       Frankie Amaya  Midfielder   5' 4"    145  19
32       Mikey Ambrose    Defender   5' 9"    165  26
33  Sebastian Anderson    Defender   5' 9"    140  17
34       Isaac Angking  Midfielder  5' 10"    160  20
35       Jalil Anibaba    Defender   6' 0"    185  31
36    Tah Brian Anunga  Midfielder  5' 11"    179  23
37      Pablo Aranguiz  Midfielder   5' 8"    143  23
38       Julian Araujo    Defender   5' 9"    154  18
39               Heber     Forward  5' 11"    170  28
40         Luis Argudo  Midfielder   5' 9"    150  24
41      Xavier Arreaga    Defender   6' 0"    165  25
42        Luis Arriaga  Midfielder   5' 7"    137  19
43        Paul Arriola  Midfielder   5' 6"    146  25
44          Yamil Asad  Midfielder  5' 10"    170  25
45     Dairon Asprilla  Midfielder  5' 11"    165  27
46      Jeff Attinella  Goalkeeper   6' 2"    190  31
47    Francis Atuahene     Forward   5' 9"    170  23
48      Eduard Atuesta  Midfielder  5' 11"    155  22
49       Micheal Azira  Midfielder  5' 10"    160  32